spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/executetestdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: 'root'
    password: '00294572'
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.206.130
    database: 1

mybatis:
  config-location: classpath:MySqlConfig.xml
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9090

